### ISSUE TITLE
Not working with dell xps 9343 in IE & Edge

### ISSUE THREAD

**Issue by Marthaarman** [jquery/jquery-mousewheel#177] opened 2017-02-06 11:55 UTC
This is not working with the trackpad of my dell xps 13 9343.

It works in chrome and mozilla & opera, but not in internet explorer & edge (Edge/14.14393) & safari

**Comment by dmethvin** [comment] 2017-02-06 12:50
This is not a bug report so I'll close it.

**Closed by dmethvin** 2017-02-06 12:50 UTC

**Comment by Marthaarman** [comment] 2017-02-06 13:20
I'n sorry but How is this not a bug? Something working on one but not on the other sounds like a bug.

**Comment by mgol** [comment] 2017-02-06 13:36
@Marthaarman "It doesn't work" doesn't give us any real information and we can't be expected to guess. You need to provide a test case (e.g. on jsfiddle.net) that will be clear in what should happen and that will fail in Edge/IE; then we can work with that.

**Comment by Marthaarman** [comment] 2017-02-06 15:05
@methvin @mgol oke true and fair... https://jsfiddle.net/vb69sshf/ this is the basic jsfiddle that does give the correct alerts as they should in chrome and firefox, however on at least my device it does not in IE(11.576.14393.0) & Edge(14.14393). So the mousewheel event is not being triggered.

If it doesn't trigger on 2 browsers on my laptop, it would make sense that it doesn't at multiple devices as well.

**Comment by dmethvin** [comment] 2017-02-06 15:14
That jsfiddle works for me on a Lenovo X1 Carbon Windows 10 on both IE11 and Edge. I think the plugin is working fine, but your setup may not be firing the events.

**Comment by Marthaarman** [comment] 2017-02-06 15:15
What do you mean specifically with 'your setup' ?

**Comment by dmethvin** [comment] 2017-02-06 15:17
Something about the difference between my working setup and your setup that doesn't work. The example you posted works fine on IE11 and Edge on my computer, so as I said it's not likely to be a bug in the plugin. You'll need to debug it further.

**Comment by Marthaarman** [comment] 2017-02-06 15:20
as it may not be a bug in the plugin, it's what i'd like to make clear that the plugin does not succeed in covering all devices. Neither does a function like this work on my machine: 
`$(window).bind('mousewheel DOMMouseScroll wheel', function(event) {mouseHandle(event);});`

This is not your fault and i'm not trying to blame, but since you're making a plugin of big use it might be interesting looking into so that your plugin can be a fix / alternative for these issues for all devices.

**Comment by Marthaarman** [comment] 2017-02-07 11:14
I found after a long search this page that explains the issue and it's a more common issue:
https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/7134034/

This states that it is neither my installation as it is not a bug on your side. 
Maybe interesting for you guys to look into though...
Sorry for disturbing you guys!

**Comment by mgol** [comment] 2017-02-07 11:23
@Marthaarman We'd normally try to workaround such a big issue but it seems there is no way to do that; no event gets fired so we have to place to hook in. It seems this bug is only fixable by Microsoft.
